site_name: 复旦大学 计算机系统基础（2026年秋季学期）
site_url: https://ics-26fall-fdu.github.io
repo_name: ICS-26Fall-FDU.github.io
repo_url: https://github.com/ICS-26Fall-FDU/ICS-26Fall-FDU.github.io
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 切换到暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式
  language: zh
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs 
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate 
    - content.code.copy
    - content.action.edit 
    - content.footnote.tooltips
    # - content.action.view
  icon:
    annotation: material/help-circle

plugins:
  - meta: 
      enabled: true
  - search:
      separator: '[\s\u200b\-]'
  - git-committers:
      repository: ICS-26Fall-FDU/ICS-26Fall-FDU.github.io
      branch: main
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid 
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list 
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      line_spans: __span 
      pygments_lang_class: true
  - pymdownx.inlinehilite 
  - pymdownx.snippets 
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist: 
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.caption

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css

nav: 
  - 首页: index.md
  - 实验: 
    - 总览: labs/index.md
    - 入门手册: labs/manual.md
    - Lab0：GitLab: labs/lab0-git-lab.md
#    - 测试: labs/test-lab.md
  - 杂项: 
    - 使用 SSH: misc/ssh.md
    - 使用 VS Code: misc/vscode_use.md
    - Linux 用户与权限: misc/user.md
  - 团队: team.md
